spring:
  profiles: 
    active: local 

---
spring:
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa: 
    show-sql: true 
    hibernate: 
      ddl-auto: create-drop
  profiles: local 
  datasource: 
    data: classpath:data-h2.sql #

server:
 port: 8888

language: java 
jdk: 
    - openjdk8 
branches: 
  only: 
    - master 
# Travis CI 서버의 Home 
cache: 
  directories: 
    - '$HOME/.m2/repository' 
    - '$HOME/.gradle'
script: "./gradlew clean build" 
# CI 실행 완료시 메일로 알람 
notifications: 
  email: 
    recipients: 
      - kwanhun21@gmail.com 
