spring:
  profiles: 
    active: local 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 


---
spring:
  profiles: local 
  datasource: 
    data: classpath:data-h2.sql #
  jpa: 
    show-sql: true 
    hibernate: 
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8888
  
# 운영 환경 
--- 
spring.profiles: set1 
spring.profiles.include: real-db 


server:
  port: 8889 
  
--- 
spring.profiles: set2 
spring.profiles.include: real-db


server:
  port: 8887