spring:
  profiles: 
    active: local 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@terraceshouses.com  
    password: superadminth05
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---

server:
  port: 8888
  
# 운영 환경 
--- 
spring.profiles: set1
spring.profiles.include: real-db

server: 
  port: 8889
  
--- 
spring.profiles: set2 
spring.profiles.include: real-db


server: 
  port: 8887
