spring: 
  profiles: 
    active: local
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail: 
    host: smtp.gmail.com
    port: 587
    username: noreply@terraceshouses.com
    password: superadminth05
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
# local 환경 
--- 
spring: 
  profiles: local 
  datasource: 
    data: classpath:data-h2.sql # 시작할때 실행시킬 script 
  jpa: 
    show-sql: true 
    hibernate: 
      ddl-auto: create-drop
  h2: 
    console: 
      enabled: true
server: 
  port: 8888

# 운영 환경 
--- 
spring.profiles: set1
spring.profiles.include: real-db
spring.http.multipart.maxFileSize: 5242880
spring.http.multipart.maxRequestSize: 5242880
server: 
  port: 8889
  
--- 
spring.profiles: set2
spring.profiles.include: real-db

server: 
  port: 8887
  
