spring:
  profiles: 
    active: local 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
---
spring:
  profiles: local 
  datasource: 
    data: classpath:data-h2.sql #local db setting
  jpa: 
    show-sql: true 
    hibernate: 
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8888
  
# 운영 환경 
--- 
spring.profiles: set1
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
spring.profiles.include: real-db

server: 
  port: 8889
  
--- 
spring.profiles: set2 
spring.profiles.include: real-db
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

server: 
  port: 8887
