spring: 
  profiles: 
    active: local
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail: 
    host: smtp.gmail.com
    port: 587
    username: noreply@terraceshouses.com
    password: superadminth05
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true

---
spring: 
  profiles: local 
  datasource: 
    data: classpath:data-h2.sql 
  jpa: 
    show-sql: true 
    hibernate: 
      ddl-auto: create-drop
  h2: 
    console: 
      enabled: true
server: 
  port: 8888

---
spring.profiles: set1
spring.profiles.include: real-db
spring.http.multipart.maxFileSize: 5242880
spring.http.multipart.maxRequestSize: 5242880
server.tomcat.uri-encoding: UTF-8
spring.http.encoding.charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring.http.encoding.enabled: true # Whether to enable http encoding support.
spring.http.encoding.force: true # Whether to force the encoding to the configured charset on HTTP requests and responses.
server: 
  port: 8889

---
spring.profiles: set2
spring.profiles.include: real-db
spring.http.multipart.maxFileSize: 5242880
spring.http.multipart.maxRequestSize: 5242880
server: 
  port: 8887

