spring:
  profiles: 
    active: local 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       
  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@terraceshouses.com  
    password: superadminth05
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---

server:
  port: 8888
  
# 운영 환경 
--- 
spring.profiles: set1
spring.profiles.include: real-db

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.‌​boot.model.naming.Ph‌​ysicalNamingStrategy‌​StandardImpl
server: 
  port: 8889
--- 
spring.profiles: set2 
spring.profiles.include: real-db
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server: 
  port: 8887
